sudo: required
os: linux
language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      env: BUILD_TYPE=RELEASE
    - os: linux
      dist: trusty
      env: BUILD_TYPE=DEBUG

install:
 - sudo add-apt-repository ppa:titas-chanda/armadillo -y
 - sudo apt-get update -qq
 - sudo apt-get install libgsl0-dev libblas-dev
 - sudo apt-get install libboost-all-dev
 - sudo apt-get install netcdf-bin libnetcdf-dev
 - sudo apt-get install libgtest-dev
 - sudo apt-get install lcov
 - sudo gem install coveralls-lcov
 - sudo apt-get install libarmadillo6 libarmadillo-dev

before_script:
  - GRIDPP_BUILD_DIR="${TRAVIS_BUILD_DIR}/build"
  - mkdir -p "${GRIDPP_BUILD_DIR}"
  - cd "${GRIDPP_BUILD_DIR}"
  - cmake -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" -DGTEST_DIR=/usr/src/gtest -DENABLE_TESTS=ON ..

script:
  - cd "${GRIDPP_BUILD_DIR}"
  - cmake --build .
  - cmake --build . --target test

after_success:
  - |
    cd "${GRIDPP_BUILD_DIR}"
    if [[ "${BUILD_TYPE}" == "DEBUG" ]]; then
       lcov --directory . --capture --output-file coverage.info
       lcov --remove coverage.info '*/src/Testing/*' '/usr/*' --output-file coverage.info # filter out system and test code
       lcov --list coverage.info # debug before upload
       sed -r "s|${TRAVIS_BUILD_DIR}/?||g" coverage.info > coverage.info.stripped
       cd ${TRAVIS_BUILD_DIR}
       coveralls-lcov --repo-token ${COVERALLS_TOKEN} ${GRIDPP_BUILD_DIR}/coverage.info.stripped # uploads to coveralls
    fi

after_failure:
  - |
    cd "${GRIDPP_BUILD_DIR}"
    LOGFILE=Testing/Temporary/LastTest.log
    [[ -f "${LOGFILE}" ]] && cat "${LOGFILE}"

#deploy:
#  provider: launchpad
#  slug: "~christian-skarby/gridpp/master"
#  oauth_token:
#    secure: "QNH5xUjkO3sP26Ncd5e8m6yV9LVP9Qhdku9uar+EDEZccy2amwNfi0RZ3mhalw8wvJUTbKwJGAzxoWCGUspg2ptRUngKNgmuLSYpCxNKJpm5bQrBBgyhAWsQFOpOqk+nEFKUiWnAe5mgP2MU89+ZWEk5TK5vBt1wclK8CaZ+dwo="
#  oauth_token_secret:
#    secure: "b/4eRApZpX3ytYcIf2Z+F5j398/zQnU8sszsZeKkZU/q5j5TF1B5dmRVODIB2JvGhXqukHUdhu7p1oja/GcAZ4a+VF3IuxIe/HaSCMHUoryeNeIzjPhpCBDY21U7kFkPjbMVJGuVcMvOXcpRJ7b5baiW/iGyFx/z3WGSN8Z7R+k="
#  on:
#    tags: true
